package:
  name: singlecell
  version: "1.0.1"

source:
  path: .

requirements:
  build:
    - python
    - setuptools
  run:
    - python
    - pandas
    - numpy

about:
  home: https://github.com/edwinv87/singlecell
  license: MIT
  summary: "A python class for managing single-cell RNA-seq data."